---
resource_registry:
  OS::TripleO::DeployedServer::ControlPlanePort: /usr/share/openstack-tripleo-heat-templates/deployed-server/deployed-neutron-port.yaml
  OS::TripleO::OVNMacAddressNetwork: OS::Heat::None
  OS::TripleO::OVNMacAddressPort: OS::Heat::None
  OS::TripleO::Compute::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::Compute::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::Compute::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::Controller::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::Controller::Ports::StorageMgmtPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage_mgmt.yaml
  OS::TripleO::Controller::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::Controller::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::CellController::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::CellController::Ports::StorageMgmtPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage_mgmt.yaml
  OS::TripleO::CellController::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::CellController::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
  OS::TripleO::CellControllerCompute::Ports::InternalApiPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_internal_api.yaml
  OS::TripleO::CellControllerCompute::Ports::StorageMgmtPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage_mgmt.yaml
  OS::TripleO::CellControllerCompute::Ports::StoragePort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_storage.yaml
  OS::TripleO::CellControllerCompute::Ports::TenantPort: /usr/share/openstack-tripleo-heat-templates/network/ports/deployed_tenant.yaml
parameter_defaults:
  DeployedNetworkEnvironment:
    net_attributes_map:
      internal_api:
        network:
          dns_domain: internalapi.multicell.
          mtu: 1500
          name: internal_api
          tags:
          - tripleo_net_idx=0
          - tripleo_vip=true
          - tripleo_network_name=InternalApi
        subnets:
          internal_api_subnet:
            cidr: 172.17.0.0/16
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: internal_api_subnet
            tags:
            - tripleo_vlan_id=20
      storage:
        network:
          dns_domain: storage.multicell.
          mtu: 1500
          name: storage
          tags:
          - tripleo_net_idx=1
          - tripleo_vip=true
          - tripleo_network_name=Storage
        subnets:
          storage_subnet:
            cidr: 172.18.0.0/16
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: storage_subnet
            tags:
            - tripleo_vlan_id=21
      storage_mgmt:
        network:
          dns_domain: storagemgmt.multicell.
          mtu: 1500
          name: storage_mgmt
          tags:
          - tripleo_net_idx=2
          - tripleo_vip=true
          - tripleo_network_name=StorageMgmt
        subnets:
          storage_mgmt_subnet:
            cidr: 172.20.0.0/16
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: storage_mgmt_subnet
            tags:
            - tripleo_vlan_id=23
      tenant:
        network:
          dns_domain: tenant.multicell.
          mtu: 1500
          name: tenant
          tags:
          - tripleo_net_idx=3
          - tripleo_network_name=Tenant
        subnets:
          tenant_subnet:
            cidr: 172.19.0.0/16
            dns_nameservers: []
            gateway_ip: null
            host_routes: []
            ip_version: 4
            name: tenant_subnet
            tags:
            - tripleo_vlan_id=22
    net_cidr_map:
      internal_api:
      - 172.17.0.0/16
      storage:
      - 172.18.0.0/16
      storage_mgmt:
      - 172.20.0.0/16
      tenant:
      - 172.19.0.0/16
    net_ip_version_map:
      external: 4
      internal_api: 4
      management: 4
      storage: 4
      storage_mgmt: 4
      tenant: 4
  DeployedServerPortMap:
    controller-0-ctlplane:
      fixed_ips:
        - ip_address: 192.168.122.101
      subnets:
        - cidr: 192.168.122.0/24
      network:
        tags:
          - 192.168.122.0/24
    compute-1-ctlplane:
      fixed_ips:
        - ip_address: 192.168.122.103
      subnets:
        - cidr: 192.168.122.0/24
      network:
        tags:
          - 192.168.122.0/24
    compute-2-ctlplane:
      fixed_ips:
        - ip_address: 192.168.122.104
      subnets:
        - cidr: 192.168.122.0/24
      network:
        tags:
          - 192.168.122.0/24
    compute-0-ctlplane:
      fixed_ips:
        - ip_address: 192.168.122.102
      subnets:
        - cidr: 192.168.122.0/24
      network:
        tags:
          - 192.168.122.0/24
  NodePortMap:
    controller-0: # overcloud-controller-0 (cell0)
      ctlplane:
        ip_address: 192.168.122.101
        ip_address_uri: 192.168.122.101
        ip_subnet: 192.168.122.0/24
      internal_api:
        ip_address: 172.17.0.101
        ip_address_uri: 172.17.0.101
        ip_subnet: 172.17.0.0/24
      storage:
        ip_address: 172.18.0.101
        ip_address_uri: 172.18.0.101
        ip_subnet: 172.18.0.0/24
      storage_mgmt:
        ip_address: 172.20.0.101
        ip_address_uri: 172.20.0.101
        ip_subnet: 172.20.0.0/24
      tenant:
        ip_address: 172.19.0.101
        ip_address_uri: 172.19.0.101
        ip_subnet: 172.19.0.0/24
    compute-1: # cell1-compute-0
      ctlplane:
        ip_address: 192.168.122.103
        ip_address_uri: 192.168.122.103
        ip_subnet: 192.168.122.0/24
      internal_api:
        ip_address: 172.17.1.103
        ip_address_uri: 172.17.1.103
        ip_subnet: 172.17.1.0/24
      storage:
        ip_address: 172.18.1.103
        ip_address_uri: 172.18.1.103
        ip_subnet: 172.18.1.0/24
      tenant:
        ip_address: 172.19.1.103
        ip_address_uri: 172.19.1.103
        ip_subnet: 172.19.1.0/24
    compute-2: # cell2-controller-compute-0 AIO
      ctlplane:
        ip_address: 192.168.122.104
        ip_address_uri: 192.168.122.104
        ip_subnet: 192.168.122.0/24
      internal_api:
        ip_address: 172.17.2.104
        ip_address_uri: 172.17.2.104
        ip_subnet: 172.17.2.0/24
      storage:
        ip_address: 172.18.2.104
        ip_address_uri: 172.18.2.104
        ip_subnet: 172.18.2.0/24
      storage_mgmt:
        ip_address: 172.20.2.104
        ip_address_uri: 172.20.2.104
        ip_subnet: 172.20.2.0/24
      tenant:
        ip_address: 172.19.2.104
        ip_address_uri: 172.19.2.104
        ip_subnet: 172.19.2.0/24
    compute-0: # cell1-controller-0
      ctlplane:
        ip_address: 192.168.122.102
        ip_address_uri: 192.168.122.102
        ip_subnet: 192.168.122.0/24
      internal_api:
        ip_address: 172.17.1.102
        ip_address_uri: 172.17.1.102
        ip_subnet: 172.17.1.0/24
      storage:
        ip_address: 172.18.1.102
        ip_address_uri: 172.18.1.102
        ip_subnet: 172.18.1.0/24
      tenant:
        ip_address: 172.19.1.102
        ip_address_uri: 172.19.1.102
        ip_subnet: 172.19.1.0/24
  CtlplaneNetworkAttributes:
    network:
      dns_domain: localdomain
      mtu: 1500
      name: ctlplane
      tags:
        - 192.168.122.0/24
    subnets:
      ctlplane-subnet:
        cidr: 192.168.122.0/24
        # FIXME(bogdando): those need to be the hypervisor virbr0 IP as a DNS resolver,
        # and the undercloud ctlplane IP as a gateway. But multi-node job in CI uses .10 for all...
        dns_nameservers: [192.168.122.10, 192.168.122.1]
        gateway_ip: 192.168.122.100
        host_routes:
          - ip_netmask: 0.0.0.0/0
            next_hop: 192.168.122.100
            default: true
        ip_version: 4
        name: ctlplane-subnet
  # Update the existing os-net-config on deployed servers for tripleo isolnet
  # This works as well in CI, where we initially configure zuul subnodes with os-net-config,
  # but is mostly targeting local libvirt/self-hosted cloud deployments, without zuul and ci-framework
  NeutronPhysicalBridge: br-ctlplane
  NetworkConfigWithAnsible: true
  ControllerNetworkConfigUpdate: true
  CellControllerNetworkConfigUpdate: true
  CellControllerComputeNetworkConfigUpdate: true
  ComputeNetworkConfigUpdate: true
  ControllerNetworkConfigTemplate: templates/single_nic_vlans/single_nic_vlans.j2
  CellControllerNetworkConfigTemplate: templates/single_nic_vlans/single_nic_vlans.j2
  CellControllerComputeNetworkConfigTemplate: templates/single_nic_vlans/single_nic_vlans.j2
  ComputeNetworkConfigTemplate: templates/single_nic_vlans/single_nic_vlans.j2
